Name:           ros-melodic-pr2-head-action
Version:        1.10.16
Release:        1%{?dist}
Summary:        ROS pr2_head_action package

Group:          Development/Libraries
License:        BSD
URL:            http://ros.org/wiki/pr2_head_action
Source0:        %{name}-%{version}.tar.gz

Requires:       ros-melodic-actionlib
Requires:       ros-melodic-geometry-msgs
Requires:       ros-melodic-kdl-parser
Requires:       ros-melodic-message-filters
Requires:       ros-melodic-orocos-kdl
Requires:       ros-melodic-pr2-controllers-msgs
Requires:       ros-melodic-roscpp
Requires:       ros-melodic-sensor-msgs
Requires:       ros-melodic-tf
Requires:       ros-melodic-tf-conversions
Requires:       ros-melodic-trajectory-msgs
BuildRequires:  ros-melodic-actionlib
BuildRequires:  ros-melodic-catkin
BuildRequires:  ros-melodic-geometry-msgs
BuildRequires:  ros-melodic-kdl-parser
BuildRequires:  ros-melodic-message-filters
BuildRequires:  ros-melodic-orocos-kdl
BuildRequires:  ros-melodic-pr2-controllers-msgs
BuildRequires:  ros-melodic-roscpp
BuildRequires:  ros-melodic-sensor-msgs
BuildRequires:  ros-melodic-tf
BuildRequires:  ros-melodic-tf-conversions
BuildRequires:  ros-melodic-trajectory-msgs

%description
The PR2 head action is a node that provides an action interface for pointing the
head of the PR2. It passes trajectory goals to the controller, and reports
success when they have finished executing.

%prep
%setup -q

%build
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/melodic/setup.sh" ]; then . "/opt/ros/melodic/setup.sh"; fi
mkdir -p obj-%{_target_platform} && cd obj-%{_target_platform}
%cmake .. \
        -UINCLUDE_INSTALL_DIR \
        -ULIB_INSTALL_DIR \
        -USYSCONF_INSTALL_DIR \
        -USHARE_INSTALL_PREFIX \
        -ULIB_SUFFIX \
        -DCMAKE_INSTALL_LIBDIR="lib" \
        -DCMAKE_INSTALL_PREFIX="/opt/ros/melodic" \
        -DCMAKE_PREFIX_PATH="/opt/ros/melodic" \
        -DSETUPTOOLS_DEB_LAYOUT=OFF \
        -DCATKIN_BUILD_BINARY_PACKAGE="1" \

make %{?_smp_mflags}

%install
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/melodic/setup.sh" ]; then . "/opt/ros/melodic/setup.sh"; fi
cd obj-%{_target_platform}
make %{?_smp_mflags} install DESTDIR=%{buildroot}

%files
/opt/ros/melodic

%changelog
* Fri Jul 26 2019 ROS Orphaned Package Maintainers <ros-orphaned-packages@googlegroups.com> - 1.10.16-1
- Autogenerated by Bloom

* Thu Sep 20 2018 ROS Orphaned Package Maintainers <ros-orphaned-packages@googlegroups.com> - 1.10.15-1
- Autogenerated by Bloom

* Thu Sep 20 2018 ROS Orphaned Package Maintainers <ros-orphaned-packages@googlegroups.com> - 1.10.15-0
- Autogenerated by Bloom

