Name:           ros-jade-pr2-calibration-controllers
Version:        1.10.13
Release:        0%{?dist}
Summary:        ROS pr2_calibration_controllers package

Group:          Development/Libraries
License:        BSD
URL:            http://ros.org/wiki/pr2_calibration_controllers
Source0:        %{name}-%{version}.tar.gz

Requires:       ros-jade-pluginlib
Requires:       ros-jade-pr2-controller-interface
Requires:       ros-jade-pr2-mechanism-controllers
Requires:       ros-jade-pr2-mechanism-model
Requires:       ros-jade-realtime-tools
Requires:       ros-jade-robot-mechanism-controllers
Requires:       ros-jade-roscpp
Requires:       ros-jade-std-msgs
BuildRequires:  ros-jade-catkin
BuildRequires:  ros-jade-pluginlib
BuildRequires:  ros-jade-pr2-controller-interface
BuildRequires:  ros-jade-pr2-mechanism-controllers
BuildRequires:  ros-jade-pr2-mechanism-model
BuildRequires:  ros-jade-realtime-tools
BuildRequires:  ros-jade-robot-mechanism-controllers
BuildRequires:  ros-jade-roscpp
BuildRequires:  ros-jade-std-msgs

%description
The pr2_calibration_controllers package contains the controllers used to bring
all the joints in the PR2 to a calibrated state.

%prep
%setup -q

%build
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/jade/setup.sh" ]; then . "/opt/ros/jade/setup.sh"; fi
mkdir -p obj-%{_target_platform} && cd obj-%{_target_platform}
%cmake .. \
        -UINCLUDE_INSTALL_DIR \
        -ULIB_INSTALL_DIR \
        -USYSCONF_INSTALL_DIR \
        -USHARE_INSTALL_PREFIX \
        -ULIB_SUFFIX \
        -DCMAKE_INSTALL_PREFIX="/opt/ros/jade" \
        -DCMAKE_PREFIX_PATH="/opt/ros/jade" \
        -DSETUPTOOLS_DEB_LAYOUT=OFF \
        -DCATKIN_BUILD_BINARY_PACKAGE="1" \

make %{?_smp_mflags}

%install
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/jade/setup.sh" ]; then . "/opt/ros/jade/setup.sh"; fi
cd obj-%{_target_platform}
make %{?_smp_mflags} install DESTDIR=%{buildroot}

%files
/opt/ros/jade

%changelog
* Tue Dec 01 2015 Devon Ash <dash@clearpathrobotics.com> - 1.10.13-0
- Autogenerated by Bloom

