Name:           ros-melodic-ethercat-trigger-controllers
Version:        1.10.15
Release:        1%{?dist}
Summary:        ROS ethercat_trigger_controllers package

Group:          Development/Libraries
License:        BSD
URL:            http://www.ros.org/wiki/ethercat_trigger_controllers
Source0:        %{name}-%{version}.tar.gz

Requires:       libtool
Requires:       libtool-ltdl-devel
Requires:       ros-melodic-diagnostic-msgs
Requires:       ros-melodic-message-runtime
Requires:       ros-melodic-pluginlib
Requires:       ros-melodic-pr2-controller-interface
Requires:       ros-melodic-realtime-tools
Requires:       ros-melodic-roscpp
Requires:       ros-melodic-rospy
Requires:       ros-melodic-std-msgs
BuildRequires:  libtool
BuildRequires:  libtool-ltdl-devel
BuildRequires:  ros-melodic-catkin
BuildRequires:  ros-melodic-diagnostic-msgs
BuildRequires:  ros-melodic-message-generation
BuildRequires:  ros-melodic-pluginlib
BuildRequires:  ros-melodic-pr2-controller-interface
BuildRequires:  ros-melodic-realtime-tools
BuildRequires:  ros-melodic-roscpp
BuildRequires:  ros-melodic-std-msgs

%description
Controllers to operate the digital output of the motor controller boards and the
projector board. This package has not been reviewed and should be considered
unstable.

%prep
%setup -q

%build
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/melodic/setup.sh" ]; then . "/opt/ros/melodic/setup.sh"; fi
mkdir -p obj-%{_target_platform} && cd obj-%{_target_platform}
%cmake .. \
        -UINCLUDE_INSTALL_DIR \
        -ULIB_INSTALL_DIR \
        -USYSCONF_INSTALL_DIR \
        -USHARE_INSTALL_PREFIX \
        -ULIB_SUFFIX \
        -DCMAKE_INSTALL_LIBDIR="lib" \
        -DCMAKE_INSTALL_PREFIX="/opt/ros/melodic" \
        -DCMAKE_PREFIX_PATH="/opt/ros/melodic" \
        -DSETUPTOOLS_DEB_LAYOUT=OFF \
        -DCATKIN_BUILD_BINARY_PACKAGE="1" \

make %{?_smp_mflags}

%install
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/melodic/setup.sh" ]; then . "/opt/ros/melodic/setup.sh"; fi
cd obj-%{_target_platform}
make %{?_smp_mflags} install DESTDIR=%{buildroot}

%files
/opt/ros/melodic

%changelog
* Thu Sep 20 2018 ROS Orphaned Package Maintainers <ros-orphaned-packages@googlegroups.com> - 1.10.15-1
- Autogenerated by Bloom

* Thu Sep 20 2018 ROS Orphaned Package Maintainers <ros-orphaned-packages@googlegroups.com> - 1.10.15-0
- Autogenerated by Bloom

